// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"fmt"
	"testing"

	"example.com/fixture/gen"
	"github.com/jackc/pgx/v5/pgtype"
)

// Comment inserts one comments row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Comment(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateCommentParams)) gen.Comment {
	t.Helper()
	n := next(t, "comments")
	arg := gen.CreateCommentParams{
		NoteID:    Note(t, db).ID,
		Body:      fmt.Sprintf("comments-body-%d", n),
		CreatedAt: pgtype.Timestamptz{Time: at(n), Valid: true},
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateComment(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Comment: %v", err)
	}
	return row
}

// CommentN inserts count rows, ascending — the shape a paging test wants.
func CommentN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateCommentParams)) []gen.Comment {
	t.Helper()
	rows := make([]gen.Comment, 0, count)
	for range count {
		rows = append(rows, Comment(t, db, mut...))
	}
	return rows
}
