// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

// Package factory builds rows the schema will accept, so a test can state
// only what it is actually about. Import it from _test files ONLY — it links
// testing, and test-only code must never reach the product binary.
package factory

import (
	"encoding/binary"
	"hash/fnv"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// epoch anchors every generated timestamp: fixed, so an assertion can name a
// value, and ascending by sequence, so rows page in insertion order.
var epoch = time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)

func at(n int64) time.Time { return epoch.Add(time.Duration(n) * time.Second) }

// ptr fills a NULLABLE column: with emit_pointers_for_null_types sqlc spells
// those *T, and a factory always has a value to point at.
func ptr[T any](v T) *T { return &v }

// seqs is the per-test, per-table counter. Keying on the testing.TB is what
// makes parallel tests independent; the cleanup keeps a long package run from
// retaining every test that ever asked for a row.
var seqs sync.Map // seqKey -> *atomic.Int64

type seqKey struct {
	t     testing.TB
	table string
}

func next(t testing.TB, table string) int64 {
	key := seqKey{t, table}
	v, loaded := seqs.LoadOrStore(key, new(atomic.Int64))
	if !loaded {
		t.Cleanup(func() { seqs.Delete(key) })
	}
	return v.(*atomic.Int64).Add(1)
}

// uuidAt is a deterministic v4-shaped UUID: the table name mixed into the
// high half, the sequence in the low half, so two tables' first rows differ.
func uuidAt(table string, n int64) pgtype.UUID {
	h := fnv.New64a()
	h.Write([]byte(table))
	var b [16]byte
	binary.BigEndian.PutUint64(b[:8], h.Sum64())
	binary.BigEndian.PutUint64(b[8:], uint64(n))
	b[6] = b[6]&0x0f | 0x40
	b[8] = b[8]&0x3f | 0x80
	return pgtype.UUID{Bytes: b, Valid: true}
}
