// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"fmt"
	"testing"

	"example.com/fixture/gen"
	"github.com/jackc/pgx/v5/pgtype"
)

// Note inserts one notes row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Note(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateNoteParams)) gen.Note {
	t.Helper()
	n := next(t, "notes")
	arg := gen.CreateNoteParams{
		Subject:   fmt.Sprintf("notes-subject-%d", n),
		Title:     fmt.Sprintf("notes-title-%d", n),
		Body:      fmt.Sprintf("notes-body-%d", n),
		Weight:    int32(n),
		CreatedAt: pgtype.Timestamptz{Time: at(n), Valid: true},
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateNote(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Note: %v", err)
	}
	return row
}

// NoteN inserts count rows, ascending — the shape a paging test wants.
func NoteN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateNoteParams)) []gen.Note {
	t.Helper()
	rows := make([]gen.Note, 0, count)
	for range count {
		rows = append(rows, Note(t, db, mut...))
	}
	return rows
}
