// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package gen

import (
	"context"
	"errors"
	"time"

	"github.com/bronystylecrazy/ultrastack/di/diag"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

// ErrNotesSubjectTitleTaken is unique constraint notes_subject_title_key (subject, title).
var ErrNotesSubjectTitleTaken = errors.New("notes: subject, title already taken")

// NotesError names what Postgres refused, so a feature branches on a sentinel
// instead of matching driver strings. Anything unrecognized is returned
// UNCHANGED — errors.Is and errors.As still reach the driver error underneath.
func NotesError(err error) error {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return err
	}
	if pgErr.Code == "42P01" {
		return ErrSchemaBehind
	}
	switch pgErr.ConstraintName {
	case "notes_subject_title_key":
		return ErrNotesSubjectTitleTaken
	}
	return err
}

// NotesCursor is one page boundary: the ordering tuple of the last row handed out.
// It is a VALUE, not an offset — a row inserted meanwhile shifts no page.
type NotesCursor struct {
	At time.Time
	ID uuid.UUID
}

// ListNotesPage runs ListNotes one row past size, so "is there more" costs no second
// query and no count. A nil cursor starts at the first page.
func (q *Queries) ListNotesPage(ctx context.Context, subject string, after *NotesCursor, size int) ([]Note, bool, error) {
	arg := ListNotesParams{Subject: subject, Limit: int32(size) + 1}
	if after != nil {
		arg.AfterAt = pgtype.Timestamptz{Time: after.At, Valid: true}
		arg.AfterID = pgtype.UUID{Bytes: after.ID, Valid: true}
	}
	rows, err := q.ListNotes(ctx, arg)
	if err != nil {
		// Shapes only, never a parameter: a query value can be a person's
		// name or a token, and diag.Wrap's contract is that a fact rides the
		// chain because a caller NAMED it.
		return nil, false, diag.Wrap(NotesError(err), "query ListNotes", "size", size, "cursor", after != nil)
	}
	if len(rows) > size {
		return rows[:size], true, nil
	}
	return rows, false, nil
}
