package main

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"
)

// The contracts half of `ultra dev` — and the reason the loop exists rather
// than a shell alias for `go run .`.
//
// Every restart regenerates the COMMITTED derived artifacts from the binary
// that was just built: openapi.json and the typed client under
// web/src/lib/api. So changing a Go response struct underlines the frontend
// that broke, in the editor, seconds later — the type error arrives before
// the browser does. The scaffolded TestContractDrift then has nothing left to
// catch, because the artifacts were never allowed to fall behind.
//
// Two rules make that safe:
//
//   - ONLY CHANGED BYTES ARE WRITTEN. `<app> client --out` writes every file
//     unconditionally, and those files live under a directory the watcher
//     would otherwise see move on every restart. Generation goes to a temp
//     dir; the sync compares and writes the differences.
//   - THE NEW BINARY ANSWERS. ULTRA_ADMIN_SOCKET=off, or a Remote command
//     would relay to the instance that is still running — the OLD one.

// devContractTimeout caps a one-shot toolbox command. A generator that hangs
// must not hang the loop.
const devContractTimeout = 60 * time.Second

// devRunProduct runs a one-shot command on the freshly built binary and
// returns its stdout.
func devRunProduct(dir, bin string, args ...string) (string, error) {
	cmd := exec.Command(bin, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "ULTRA_ADMIN_SOCKET=off")
	var out, errBuf strings.Builder
	cmd.Stdout, cmd.Stderr = &out, &errBuf
	setProcessGroup(cmd)
	if err := cmd.Start(); err != nil {
		return "", err
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	select {
	case err := <-done:
		if err != nil {
			msg := firstLineOf(errBuf.String())
			if msg == "" {
				msg = err.Error()
			}
			return out.String(), errors.New(msg)
		}
		return out.String(), nil
	case <-time.After(devContractTimeout):
		signalGroup(cmd.Process, syscall.SIGKILL)
		return "", errors.New(strings.Join(args, " ") + " timed out")
	}
}

// devHasCommand reports whether a product's `help` listing advertises a
// command. The toolbox is assembled from whatever presets a product wires, so
// `openapi` exists only with the api preset and `infra compose` only once
// dev-infra is in the build — asking the binary is the only honest probe, and
// it is re-asked after every build because the answer can change.
//
// A listing row is indented and separated by at least two spaces, and nested
// command names contain spaces ("infra compose"), so the name is everything
// before the first double space. That holds for the cobra-shaped listing a
// current product prints and for the flat "  %-20s %s" an older product still
// prints — the probe must work against both, because the product on the bench
// pins whatever framework version it pins.
func devHasCommand(help, name string) bool {
	for _, line := range strings.Split(help, "\n") {
		if !strings.HasPrefix(line, "  ") {
			continue
		}
		field, _, _ := strings.Cut(strings.TrimSpace(line), "  ")
		if strings.TrimSpace(field) == name {
			return true
		}
	}
	return false
}

// writeIfChanged writes content only when the bytes on disk differ, and
// reports whether it wrote. Not an optimization: an unconditional write moves
// the mtime, and something is always watching these files.
func writeIfChanged(path string, content []byte) (bool, error) {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, content) {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, content, 0o644)
}

// syncGenerated mirrors a freshly generated tree onto the committed one,
// writing only the files whose bytes moved, and returns those paths relative
// to dst.
//
// It also removes the files dst still holds that src no longer emits — but
// only the ones carrying the emitter's "Code generated by" banner. A renamed
// operation must not leave a dead module the frontend can still import, and a
// hand-added file in the same directory must not be collateral damage.
func syncGenerated(src, dst string) ([]string, error) {
	var changed []string
	emitted := map[string]bool{}
	err := filepath.WalkDir(src, func(p string, e fs.DirEntry, err error) error {
		if err != nil || e.IsDir() {
			return err
		}
		rel, err := filepath.Rel(src, p)
		if err != nil {
			return err
		}
		emitted[filepath.ToSlash(rel)] = true
		content, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		wrote, err := writeIfChanged(filepath.Join(dst, rel), content)
		if err != nil {
			return err
		}
		if wrote {
			changed = append(changed, filepath.ToSlash(rel))
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	err = filepath.WalkDir(dst, func(p string, e fs.DirEntry, err error) error {
		if err != nil || e.IsDir() {
			return err
		}
		rel, err := filepath.Rel(dst, p)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if emitted[rel] || !isGeneratedFile(p) {
			return nil
		}
		if err := os.Remove(p); err != nil {
			return err
		}
		changed = append(changed, rel)
		return nil
	})
	sort.Strings(changed)
	return changed, err
}

// isGeneratedFile reads the head of a file and looks for the marker every
// ultrastack emitter writes. It is the license to delete.
func isGeneratedFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	head := make([]byte, 256)
	n, _ := f.Read(head)
	return bytes.Contains(head[:n], []byte("Code generated by"))
}

// refreshContracts regenerates the derived artifacts from the binary at bin
// and returns the banner segment describing what moved — "" when the product
// has no contracts to refresh at all (a --bare product wires no api preset,
// so its toolbox has no openapi command and there is nothing to say).
func (d *devLoop) refreshContracts(bin string) string {
	help, err := devRunProduct(d.root, bin, "help")
	if err != nil {
		return "" // the binary cannot even list its toolbox; serve will say why
	}

	// has answers for the whole tree, not just its top level: a current
	// product's root listing shows the PARENT ("infra"), so a nested verb is
	// confirmed by asking that parent for its own listing. An older product
	// lists every full name flat, and the first check already finds it.
	has := func(name string) bool {
		if devHasCommand(help, name) {
			return true
		}
		parent, leaf, nested := strings.Cut(name, " ")
		if !nested || !devHasCommand(help, parent) {
			return false
		}
		sub, err := devRunProduct(d.root, bin, "help", parent)
		if err != nil {
			return false
		}
		return devHasCommand(sub, leaf) || devHasCommand(sub, name)
	}

	var changed []string
	generated := false

	if has("openapi") {
		generated = true
		doc, err := devRunProduct(d.root, bin, "openapi")
		if err != nil {
			return "contracts FAILED — openapi: " + err.Error()
		}
		wrote, err := writeIfChanged(filepath.Join(d.root, contractFile), []byte(doc))
		if err != nil {
			return "contracts FAILED — " + err.Error()
		}
		if wrote {
			changed = append(changed, contractFile)
		}
	}

	// The typed client is refreshed only where the product already keeps one:
	// ultra dev refreshes committed artifacts, it does not invent them.
	if has("client") && isDir(filepath.Join(d.root, clientDir)) {
		generated = true
		tmp, err := os.MkdirTemp("", "ultra-dev-client-")
		if err != nil {
			return "contracts FAILED — " + err.Error()
		}
		defer os.RemoveAll(tmp)
		if _, err := devRunProduct(d.root, bin, "client", "--out", tmp); err != nil {
			return "contracts FAILED — client: " + err.Error()
		}
		names, err := syncGenerated(tmp, filepath.Join(d.root, clientDir))
		if err != nil {
			return "contracts FAILED — " + err.Error()
		}
		changed = append(changed, names...)
	}

	// Dev-infra's compose file is derived from the graph too, so a new
	// dependency in the wiring shows up in docker-compose.dev.yml on the same
	// restart. The command lands with the dev-infra preset; a product without
	// it simply has no such verb, and that is not an event worth a line.
	if has("infra compose") {
		devRunProduct(d.root, bin, "infra", "compose")
	}

	if !generated {
		return ""
	}
	if len(changed) == 0 {
		return "contracts unchanged"
	}
	return fmt.Sprintf("contracts refreshed (%s)", devPlural(len(changed), "file"))
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func devPlural(n int, unit string) string {
	if n == 1 {
		return "1 " + unit
	}
	return fmt.Sprintf("%d %ss", n, unit)
}
