package main

import "testing"

// TestSingularMatchesSqlc pins the inflection port against the values
// github.com/jinzhu/inflection v1.0.0 actually returns — generated by running
// it, not by reasoning about English. Every row is a table name whose model
// type the plugin has to spell the same way sqlc's own codegen does; a drift
// here is a product that does not compile, so the table is deliberately long
// and includes the ugly cases (viruses, buzzes, leaves) where jinzhu is
// wrong-but-authoritative.
func TestSingularMatchesSqlc(t *testing.T) {
	for _, c := range []struct{ plural, want string }{
		{"notes", "note"}, {"comments", "comment"}, {"shapes", "shape"},
		{"users", "user"}, {"people", "person"}, {"children", "child"},
		{"men", "man"}, {"boxes", "box"}, {"buses", "bus"},
		{"statuses", "status"}, {"aliases", "alias"}, {"matrices", "matrix"},
		{"vertices", "vertex"}, {"indices", "index"}, {"quizzes", "quiz"},
		{"databases", "database"}, {"series", "series"}, {"species", "species"},
		{"news", "news"}, {"movies", "movie"}, {"cookies", "cookie"},
		{"categories", "category"}, {"companies", "company"},
		{"addresses", "address"}, {"classes", "class"}, {"leaves", "leafe"},
		{"lives", "life"}, {"knives", "knife"}, {"wolves", "wolf"},
		{"hives", "hive"}, {"motives", "motive"}, {"octopi", "octopus"},
		{"viruses", "viruse"}, {"analyses", "analysis"},
		{"diagnoses", "diagnosis"}, {"theses", "thesis"}, {"crises", "crisis"},
		{"axes", "axis"}, {"mice", "mouse"}, {"oxen", "ox"}, {"shoes", "shoe"},
		{"heroes", "hero"}, {"order_items", "order_item"},
		{"api_keys", "api_key"}, {"sessions", "session"},
		{"audit_logs", "audit_log"}, {"invoices", "invoice"}, {"taxes", "tax"},
		{"photos", "photo"}, {"cities", "city"}, {"countries", "country"},
		{"identities", "identity"}, {"properties", "property"},
		{"sheep", "sheep"}, {"fish", "fish"}, {"equipment", "equipment"},
		{"money", "money"}, {"police", "police"}, {"jeans", "jeans"},
		{"rice", "rice"}, {"information", "information"},
		{"payment_methods", "payment_method"}, {"webhooks", "webhook"},
		{"feature_flags", "feature_flag"}, {"teams", "team"},
		{"memberships", "membership"}, {"accesses", "access"},
		{"buzzes", "buzze"}, {"processes", "process"}, {"phases", "phase"},
		{"bases", "basis"}, {"types", "type"}, {"keys", "key"},

		// sqlc corrects jinzhu on these five before delegating, so the port
		// must too — jinzhu alone answers campu, metum, calory, wafe,
		// metadatum.
		{"campus", "campus"}, {"meta", "meta"}, {"calories", "calorie"},
		{"waves", "wave"}, {"metadata", "metadata"},
	} {
		if got := singular(c.plural); got != c.want {
			t.Errorf("singular(%q) = %q, sqlc says %q", c.plural, got, c.want)
		}
	}
}

// TestGoName pins sqlc's StructName, including the one initialism its default
// configuration carries.
func TestGoName(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"notes", "Notes"},
		{"order_items", "OrderItems"},
		{"id", "ID"},
		{"note_id", "NoteID"},
		{"after_at", "AfterAt"},
		{"created_at", "CreatedAt"},
		{"api_key", "ApiKey"},
		{"v2col", "V2Col"}, // strings.Title's rule: a letter after a digit starts a word
		{"2fa", "_2Fa"},    // a leading digit is not a Go identifier
	} {
		if got := goName(c.in); got != c.want {
			t.Errorf("goName(%q) = %q, want %q", c.in, got, c.want)
		}
	}
	if got := modelName("notes"); got != "Note" {
		t.Errorf("modelName(notes) = %q, want Note", got)
	}
}

func TestLowerCamel(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"Subject", "subject"},
		{"NoteID", "noteID"},
		{"ID", "id"},
		{"Type", "type_"}, // a column named `type` is a legal column, not a legal parameter
	} {
		if got := lowerCamel(c.in); got != c.want {
			t.Errorf("lowerCamel(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}
