package main

// What the ultra sqlc plugin writes.
//
// sqlc's own Go codegen answers "what do these queries look like in Go". It
// stops exactly where every product then writes the same four things by hand:
// a handle that can open a transaction, a bridge for work that must commit
// with the caller, keyset paging around a cursor query, and test rows the
// schema will accept. Those four are DERIVABLE from the schema sqlc already
// parsed, so they are generated here rather than remembered per product.
//
// Nothing in this file guesses: a wrapper appears when a query's compiled
// shape proves it is a keyset page, a sentinel appears when the migration
// declares the constraint, a factory appears when every column its insert
// demands has a deterministic value IN THE TYPE SQLC EMITTED for it
// (sqlcoverride.go resolves that). A table that fails a test gets NO output
// and a named reason in ultra.go — silence would be the one failure mode worse
// than the hand-written code this replaces.

import (
	"cmp"
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"sort"
	"strings"
	"unicode"
)

// genHeader tops every emitted file. It says which tool and which command —
// an agent that finds this file must not edit it, and must know the verb.
const genHeader = "// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate\n\n"

// pgType is one Postgres type's TWO Go renderings under sqlc's pgx/v5 driver:
// what a NOT NULL column gets, and what a nullable one gets. Both are sqlc's
// answers, transcribed from real output rather than invented here — a factory
// only compiles if it agrees with the params struct beside it. A type absent
// from this table is not guessed: its table loses its factory and says why.
type pgType struct {
	notNull string
	null    string
	// pointer reports whether emit_pointers_for_null_types moves the nullable
	// rendering to *notNull. pgx/v5 keeps uuid, the date/time family and the
	// []byte types on their own spelling either way, so the flag is per type.
	pointer bool
}

const pgtypePkg = "github.com/jackc/pgx/v5/pgtype"

var pgTypes = map[string]pgType{
	"text":        {"string", "pgtype.Text", true},
	"varchar":     {"string", "pgtype.Text", true},
	"bpchar":      {"string", "pgtype.Text", true},
	"char":        {"string", "pgtype.Text", true},
	"name":        {"string", "pgtype.Text", true},
	"citext":      {"string", "pgtype.Text", true},
	"bool":        {"bool", "pgtype.Bool", true},
	"boolean":     {"bool", "pgtype.Bool", true},
	"int2":        {"int16", "pgtype.Int2", true},
	"smallint":    {"int16", "pgtype.Int2", true},
	"int4":        {"int32", "pgtype.Int4", true},
	"integer":     {"int32", "pgtype.Int4", true},
	"int8":        {"int64", "pgtype.Int8", true},
	"bigint":      {"int64", "pgtype.Int8", true},
	"float4":      {"float32", "pgtype.Float4", true},
	"real":        {"float32", "pgtype.Float4", true},
	"float8":      {"float64", "pgtype.Float8", true},
	"uuid":        {"pgtype.UUID", "pgtype.UUID", false},
	"timestamptz": {"pgtype.Timestamptz", "pgtype.Timestamptz", false},
	"timestamp":   {"pgtype.Timestamp", "pgtype.Timestamp", false},
	"date":        {"pgtype.Date", "pgtype.Date", false},
	"json":        {"[]byte", "[]byte", false},
	"jsonb":       {"[]byte", "[]byte", false},
	"bytea":       {"[]byte", "[]byte", false},
}

// factoryValue is a deterministic value of goType — the type sqlc RESOLVED for
// this column, whatever route it took there. dbType only ever chooses between
// two values of one Go type (a json column must hold valid JSON; a bytea is
// happier holding the row's own name). needs is what the expression refers to,
// so a file's imports follow the literals it ended up with. ok is false for a
// type this generator has no defensible value for — the caller reports that
// instead of writing something that will not compile.
func factoryValue(goType, imp, dbType, table, col, seq string) (expr string, needs []string, ok bool) {
	if base, isPtr := strings.CutPrefix(goType, "*"); isPtr {
		expr, needs, ok := factoryValue(base, imp, dbType, table, col, seq)
		return "ptr(" + expr + ")", needs, ok
	}
	str := fmt.Sprintf("fmt.Sprintf(%q, %s)", table+"-"+col+"-%d", seq)
	switch goType {
	case "string":
		return str, []string{"fmt"}, true
	case "bool":
		return "false", nil, true
	case "int16":
		return "int16(" + seq + ")", nil, true
	case "int32":
		return "int32(" + seq + ")", nil, true
	case "int64":
		return seq, nil, true
	case "float32":
		return "float32(" + seq + ")", nil, true
	case "float64":
		return "float64(" + seq + ")", nil, true
	case "[]byte":
		if dbType == "json" || dbType == "jsonb" {
			return `[]byte("{}")`, nil, true
		}
		return "[]byte(" + str + ")", []string{"fmt"}, true
	case "pgtype.Text":
		return "pgtype.Text{String: " + str + ", Valid: true}", []string{"fmt", pgtypePkg}, true
	case "pgtype.Bool":
		return "pgtype.Bool{Bool: false, Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Int2":
		return "pgtype.Int2{Int16: int16(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Int4":
		return "pgtype.Int4{Int32: int32(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Int8":
		return "pgtype.Int8{Int64: " + seq + ", Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Float4":
		return "pgtype.Float4{Float32: float32(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Float8":
		return "pgtype.Float8{Float64: float64(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.UUID":
		// uuidAt is factory-local and already returns a pgtype.UUID, so this
		// spelling costs the file no import of its own.
		return fmt.Sprintf("uuidAt(%q, %s)", table, seq), nil, true
	case "pgtype.Timestamptz":
		return "pgtype.Timestamptz{Time: at(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Timestamp":
		return "pgtype.Timestamp{Time: at(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "pgtype.Date":
		return "pgtype.Date{Time: at(" + seq + "), Valid: true}", []string{pgtypePkg}, true
	case "time.Time":
		// at() is factory-local too, so a time.Time fill needs no import.
		return "at(" + seq + ")", nil, true
	case "uuid.UUID":
		// uuid.UUID is [16]byte, so the deterministic value already on hand
		// converts without a second generator.
		if imp == "" {
			imp = "github.com/google/uuid"
		}
		return fmt.Sprintf("uuid.UUID(uuidAt(%q, %s).Bytes)", table, seq), []string{imp}, true
	}
	return "", nil, false
}

// ---- the analysis ----

// tableGen is everything the emitter concluded about one table.
type tableGen struct {
	name   string // the SQL table, "notes"
	ident  sqlcIdent
	model  string // sqlc's row struct, "Note"
	export string // the plural Go stem for this table's symbols, "Notes"
	cols   []sqlcColumn

	uniques []uniqueGen
	pages   []pageGen
	create  *sqlcQuery        // the insert this table's factory drives
	fkByCol map[string]string // column -> the parent table a factory must create first
	// types is the product's type policy, shared by every table in one run:
	// this sqlc.yaml's overrides and its nullable rendering.
	types typeConfig
	// fills is what the factory sets, resolved once in planFactory so the
	// emitter and the refusal below can never be two opinions about a column.
	fills []colFill
	// noFactory, when set, is the reason — reported in ultra.go rather than
	// swallowed, so "where is my factory" is never a mystery.
	noFactory string
	// noPages is the same channel for a query that IS a keyset page but got no
	// wrapper: "<Query> — <reason>", one per dropped query. Refusing is right;
	// refusing quietly is the mystery this generator exists to avoid.
	noPages []string
}

// colFill is one column a factory sets, already spelled in the type sqlc
// emitted for it.
type colFill struct {
	field string
	expr  string
	needs []string
}

type uniqueGen struct {
	constraint string // exactly what pgconn.PgError.ConstraintName carries
	sentinel   string // ErrNotesSubjectTaken
	cols       []string
}

// pageGen is one query whose compiled shape IS a keyset page.
type pageGen struct {
	query                        string // ListNotes
	cursor                       string // NotesCursor
	row                          string // the element type of the generated method's result
	params                       string // ListNotesParams
	atField, idField, limitField string
	owners                       []ownerArg
}

type ownerArg struct {
	arg    string // the Go parameter, lower camel
	field  string // the params struct field
	goType string
}

// analyze turns a decoded request plus the schema facts scraped from the
// migrations into the per-table plan the emitters render.
func analyze(req *sqlcRequest, facts schemaFacts, types typeConfig) []tableGen {
	var out []tableGen
	for _, s := range req.Catalog.Schemas {
		if s.Name != types.schema {
			continue // pg_catalog and friends ride along in every request
		}
		for _, t := range s.Tables {
			g := tableGen{
				name:    t.Rel.Name,
				ident:   t.Rel,
				model:   modelName(t.Rel.Name),
				export:  goName(t.Rel.Name),
				cols:    t.Columns,
				fkByCol: facts.fks[t.Rel.Name],
				types:   types,
			}
			for _, u := range facts.uniques[g.name] {
				g.uniques = append(g.uniques, uniqueGen{
					constraint: u.name,
					sentinel:   sentinelName(u),
					cols:       u.cols,
				})
			}
			out = append(out, g)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })

	byName := map[string]*tableGen{}
	for i := range out {
		byName[out[i].name] = &out[i]
	}
	for i := range req.Queries {
		q := &req.Queries[i]
		if q.InsertIntoTable != nil {
			if g := byName[q.InsertIntoTable.Name]; g != nil && g.create == nil && q.Cmd == ":one" {
				g.create = q
			}
			continue
		}
		p, table, reason := detectPage(q, byName, types)
		switch {
		case p != nil:
			table.pages = append(table.pages, *p)
		case reason != "":
			table.noPages = append(table.noPages, fmt.Sprintf("%s — %s", q.Name, reason))
		}
	}
	for i := range out {
		out[i].fills, out[i].noFactory = planFactory(&out[i], byName)
	}
	return out
}

// sentinelName turns a constraint into a Go sentinel: notes_subject_key
// becomes ErrNotesSubjectTaken. The DB object's own name is the source, so
// the sentinel and the error Postgres reports can never drift apart.
func sentinelName(u uniqueFact) string {
	stem := u.name
	for _, suffix := range []string{"_key", "_idx", "_index", "_unique", "_uniq", "_uq"} {
		stem = strings.TrimSuffix(stem, suffix)
	}
	return "Err" + goName(stem) + "Taken"
}

// tupleRe finds a keyset tuple compare: (created_at, id) < (…, …).
var tupleRe = regexp.MustCompile(`\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*[<>]\s*\(`)

// detectPage reports whether a compiled query IS a keyset page over one
// table: a :many with a nullable (timestamptz, uuid) narg pair compared as a
// tuple against the columns it orders by, plus an integer limit. Shape, not
// naming — a query that merely mentions a cursor gets nothing.
func detectPage(q *sqlcQuery, byName map[string]*tableGen, types typeConfig) (*pageGen, *tableGen, string) {
	if q.Cmd != ":many" || len(q.Columns) == 0 {
		return nil, nil, ""
	}
	tuple := tupleRe.FindStringSubmatch(strings.ToLower(q.Text))
	if tuple == nil || !strings.Contains(strings.ToLower(q.Text), "order by") {
		return nil, nil, ""
	}
	var at, id, limit *sqlcColumn
	var owners []sqlcColumn
	for i := range q.Params {
		c := q.Params[i].Column
		switch {
		case c.IsNamedParam && !c.NotNull && baseType(c.Type.Name) == "timestamptz" && at == nil:
			at = &q.Params[i].Column
		case c.IsNamedParam && !c.NotNull && baseType(c.Type.Name) == "uuid" && id == nil:
			id = &q.Params[i].Column
		case !c.IsNamedParam && isIntType(baseType(c.Type.Name)) && limit == nil:
			limit = &q.Params[i].Column
		default:
			owners = append(owners, c)
		}
	}
	if at == nil || id == nil || limit == nil {
		return nil, nil, ""
	}
	// The tuple must be the ORDER BY, or the "one row past the end" trick
	// reads a page nobody asked for.
	order := strings.ToLower(q.Text[strings.LastIndex(strings.ToLower(q.Text), "order by"):])
	if !strings.Contains(order, tuple[1]) || !strings.Contains(order, tuple[2]) {
		return nil, nil, ""
	}
	table := byName[q.Columns[0].Table.GetName()]
	if table == nil {
		return nil, nil, ""
	}
	// emitPage writes the cursor into the two narg fields as pgtype literals,
	// so a product whose overrides moved them elsewhere gets no wrapper rather
	// than one that does not compile. From here on the table is known, so the
	// refusal carries its reason instead of vanishing.
	if atType, _ := types.goTypeOf(at.Table, *at); atType != "pgtype.Timestamptz" {
		return nil, table, fmt.Sprintf("the cursor param %s is %s, not pgtype.Timestamptz — an override moved it", at.Name, atType)
	}
	if idType, _ := types.goTypeOf(id.Table, *id); idType != "pgtype.UUID" {
		return nil, table, fmt.Sprintf("the cursor param %s is %s, not pgtype.UUID — an override moved it", id.Name, idType)
	}
	p := pageGen{
		query:      q.Name,
		cursor:     strings.TrimPrefix(q.Name, "List") + "Cursor",
		row:        rowType(q, table),
		params:     q.Name + "Params",
		atField:    goName(at.Name),
		idField:    goName(id.Name),
		limitField: goName(limit.Name),
	}
	for _, c := range owners {
		goType, _ := types.goTypeOf(c.Table, c)
		if goType == "" || !c.NotNull || c.IsArray {
			// An owner we cannot type is not a page we can write — and that is
			// worth saying, for the same reason the cursor checks above are.
			return nil, table, fmt.Sprintf("the filter param %s is %s — a page wrapper cannot pass it through", c.Name, cmp.Or(goType, c.Type.Name))
		}
		p.owners = append(p.owners, ownerArg{arg: lowerCamel(goName(c.Name)), field: goName(c.Name), goType: goType})
	}
	return &p, table, ""
}

// rowType is the element type of the generated method's slice: sqlc reuses
// the table's model when a query returns that table's columns unchanged
// (`select *`), and mints <Query>Row otherwise.
func rowType(q *sqlcQuery, t *tableGen) string {
	if len(q.Columns) != len(t.cols) {
		return q.Name + "Row"
	}
	for i, c := range q.Columns {
		if c.Name != t.cols[i].Name || c.Table.GetName() != t.name {
			return q.Name + "Row"
		}
	}
	return t.model
}

func (i *sqlcIdent) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

// planFactory resolves what this table's factory fills, or the reason it gets
// none. Every column goes through typeConfig.goTypeOf — the same resolution
// sqlc ran for the params struct — so an override, a nullable column, or a
// foreign key whose parent id is spelled differently is decided HERE, once,
// and the emitter only renders the answer.
func planFactory(t *tableGen, byName map[string]*tableGen) ([]colFill, string) {
	if t.create == nil {
		return nil, "no :one insert query — a factory has nothing to call"
	}
	var fills []colFill
	for _, p := range t.create.Params {
		c := p.Column
		if c.IsArray {
			return nil, fmt.Sprintf("column %s is an array — no defensible default", c.Name)
		}
		goType, imp := t.types.goTypeOf(&t.ident, c)
		if goType == "" {
			return nil, fmt.Sprintf("column %s is %s, which has no deterministic default", c.Name, c.Type.Name)
		}
		if parent := t.fkByCol[c.Name]; parent != "" {
			expr, reason := parentFill(t, byName, parent, c.Name, goType)
			if reason != "" {
				return nil, reason
			}
			fills = append(fills, colFill{field: goName(c.Name), expr: expr})
			continue
		}
		expr, needs, ok := factoryValue(goType, imp, baseType(c.Type.Name), t.name, c.Name, "n")
		if !ok {
			return nil, fmt.Sprintf("column %s is %s (%s in Go), which has no deterministic default", c.Name, c.Type.Name, goType)
		}
		fills = append(fills, colFill{field: goName(c.Name), expr: expr, needs: needs})
	}
	return fills, ""
}

// parentFill takes a foreign key from a row the factory creates first. The two
// sides must be spelled the SAME way — an override or a nullable column can
// give a child's fk a type its parent's id does not have, and a conversion
// this generator invented would be a guess.
func parentFill(t *tableGen, byName map[string]*tableGen, parent, col, goType string) (expr, reason string) {
	g := byName[parent]
	switch {
	case parent == t.name:
		return "", fmt.Sprintf("column %s references its own table — a factory would not terminate", col)
	case g == nil || g.create == nil:
		return "", fmt.Sprintf("column %s references %s, which has no factory of its own", col, parent)
	}
	i := slices.IndexFunc(g.cols, func(p sqlcColumn) bool { return p.Name == "id" })
	if i < 0 {
		return "", fmt.Sprintf("column %s references %s, which has no id column to take", col, parent)
	}
	id, _ := g.types.goTypeOf(&g.ident, g.cols[i])
	take := modelName(parent) + "(t, db).ID"
	switch goType {
	case id:
		return take, ""
	case "*" + id:
		return "ptr(" + take + ")", ""
	}
	return "", fmt.Sprintf("column %s is %s but %s.id is %s — a factory cannot bridge them", col, goType, parent, id)
}

func baseType(s string) string {
	if i := strings.LastIndex(s, "."); i >= 0 {
		s = s[i+1:]
	}
	return strings.ToLower(s)
}

func isIntType(s string) bool {
	switch s {
	case "int2", "int4", "int8", "smallint", "integer", "bigint":
		return true
	}
	return false
}

func lowerCamel(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	// An initialism keeps its shape until the first lowercase run: IDToken
	// becomes idToken, ID becomes id.
	i := 0
	for i < len(r) && unicode.IsUpper(r[i]) {
		i++
	}
	if i > 1 && i < len(r) {
		i--
	}
	for j := 0; j < i; j++ {
		r[j] = unicode.ToLower(r[j])
	}
	return goKeyword(string(r))
}

// goKeyword keeps a column named `type` or `range` from becoming an illegal
// parameter name.
func goKeyword(s string) string {
	switch s {
	case "break", "case", "chan", "const", "continue", "default", "defer", "else",
		"fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
		"map", "package", "range", "return", "select", "struct", "switch", "type", "var":
		return s + "_"
	}
	return s
}

// ---- the emitters ----

// emitAll renders every file the plugin contributes. genImport is the import
// path of the sqlc output package, which the factory package needs.
func emitAll(tables []tableGen, genImport string) ([]outFile, error) {
	files := []outFile{}
	shared, err := gofmtGo(emitShared(tables))
	if err != nil {
		return nil, err
	}
	files = append(files, outFile{"ultra.go", shared})

	var factories []outFile
	// Every table gets a file even with no constraints and no page query: the
	// 42P01 arm alone is worth a classifier, and its absence would read as a
	// table the plugin failed to see.
	for i := range tables {
		t := &tables[i]
		body, err := gofmtGo(emitTable(t))
		if err != nil {
			return nil, fmt.Errorf("table %s: %w", t.name, err)
		}
		files = append(files, outFile{"ultra_" + t.name + ".go", body})
		if t.noFactory != "" {
			continue
		}
		f, err := gofmtGo(emitFactory(t, genImport))
		if err != nil {
			return nil, fmt.Errorf("factory %s: %w", t.name, err)
		}
		factories = append(factories, outFile{"factory/" + t.name + ".go", f})
	}
	if len(factories) > 0 {
		base, err := gofmtGo(emitFactoryShared())
		if err != nil {
			return nil, err
		}
		files = append(files, outFile{"factory/ultra.go", base})
		files = append(files, factories...)
	}
	return files, nil
}

// writeImports renders the two groups gofmt would not reorder for us —
// stdlib, blank line, everything else — each sorted.
func writeImports(b *strings.Builder, std, ext []string) {
	sort.Strings(std)
	sort.Strings(ext)
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString("\n")
	for _, p := range ext {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
}

func gofmtGo(src string) ([]byte, error) {
	b, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("the plugin rendered invalid Go: %w\n%s", err, src)
	}
	return b, nil
}

func emitShared(tables []tableGen) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString(`package gen

import (
	"context"
	"errors"

	"github.com/bronystylecrazy/ultrastack/contrib/pg"
	"github.com/jackc/pgx/v5"
)

// DB is the product's one handle on Postgres, and the only thing a Store
// holds. It reaches a querier two ways and no third: Q() for a single
// statement, Atomic() for a unit of work.
type DB struct{ db *pg.DB }

func NewDB(db *pg.DB) *DB { return &DB{db: db} }

// Q is the querier outside a transaction — one statement is already atomic.
func (d *DB) Q() *Queries { return New(d.db.Pool) }

// Atomic runs fn as one transaction: commit when it returns nil, roll back
// otherwise. fn MAY RUN TWICE, because a serialization failure is retried —
// so it must carry no state across the call and do nothing outside the
// database (no publish, no email, no counter).
func (d *DB) Atomic(ctx context.Context, fn func(*Queries) error) error {
	return pg.Atomic(ctx, d.db, func(tx pgx.Tx) error { return fn(New(tx)) })
}

// Tx exposes the handle this querier runs on, so work that must commit WITH
// the caller (jobs.EnqueueTx) joins the transaction instead of opening a
// second one that can commit alone.
func (q *Queries) Tx() DBTX { return q.db }

// ErrSchemaBehind is what 42P01 means in practice: the binary is ahead of the
// database. Every <Table>Error maps it, so no product learns the code.
var ErrSchemaBehind = errors.New("relation does not exist — run ./app migrate up")
`)
	var skipped []string
	for _, t := range tables {
		if t.noFactory != "" {
			skipped = append(skipped, fmt.Sprintf("//   %s — %s", t.name, t.noFactory))
		}
	}
	if len(skipped) > 0 {
		b.WriteString("\n// Tables with no generated factory, and why. Write one by hand in a\n" +
			"// _test file, or give the column a type this generator can default:\n")
		b.WriteString(strings.Join(skipped, "\n"))
		b.WriteString("\n")
	}
	var dropped []string
	for _, t := range tables {
		for _, why := range t.noPages {
			dropped = append(dropped, "//   "+why)
		}
	}
	if len(dropped) > 0 {
		b.WriteString("\n// Keyset queries with no generated <Query>Page wrapper, and why. Call the\n" +
			"// sqlc method directly and fill the cursor params yourself, or drop the\n" +
			"// override that moved them:\n")
		b.WriteString(strings.Join(dropped, "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

func emitTable(t *tableGen) string {
	var b strings.Builder
	b.WriteString(genHeader)
	std, ext := []string{"errors"}, []string{"github.com/jackc/pgx/v5/pgconn"}
	if len(t.pages) > 0 {
		std = append(std, "context", "time")
		ext = append(ext, "github.com/bronystylecrazy/ultrastack/di/diag",
			"github.com/google/uuid", "github.com/jackc/pgx/v5/pgtype")
	}
	b.WriteString("package gen\n\n")
	writeImports(&b, std, ext)

	for _, u := range t.uniques {
		fmt.Fprintf(&b, "// %s is unique constraint %s (%s).\nvar %s = errors.New(%q)\n\n",
			u.sentinel, u.constraint, strings.Join(u.cols, ", "), u.sentinel,
			t.name+": "+strings.Join(u.cols, ", ")+" already taken")
	}

	fmt.Fprintf(&b, `// %sError names what Postgres refused, so a feature branches on a sentinel
// instead of matching driver strings. Anything unrecognized is returned
// UNCHANGED — errors.Is and errors.As still reach the driver error underneath.
func %sError(err error) error {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return err
	}
	if pgErr.Code == "42P01" {
		return ErrSchemaBehind
	}
`, t.export, t.export)
	if len(t.uniques) > 0 {
		b.WriteString("\tswitch pgErr.ConstraintName {\n")
		for _, u := range t.uniques {
			fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %s\n", u.constraint, u.sentinel)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn err\n}\n")

	for _, p := range t.pages {
		emitPage(&b, t, p)
	}
	return b.String()
}

func emitPage(b *strings.Builder, t *tableGen, p pageGen) {
	// The element type follows sqlc's own rendering: pointers when the
	// product's gen.go says emit_result_struct_pointers.
	elem := p.row
	if t.types.resultPointers {
		elem = "*" + p.row
	}
	fmt.Fprintf(b, `
// %s is one page boundary: the ordering tuple of the last row handed out.
// It is a VALUE, not an offset — a row inserted meanwhile shifts no page.
type %s struct {
	At time.Time
	ID uuid.UUID
}

// %sPage runs %s one row past size, so "is there more" costs no second
// query and no count. A nil cursor starts at the first page.
func (q *Queries) %sPage(ctx context.Context`, p.cursor, p.cursor, p.query, p.query, p.query)
	for _, o := range p.owners {
		fmt.Fprintf(b, ", %s %s", o.arg, o.goType)
	}
	fmt.Fprintf(b, ", after *%s, size int) ([]%s, bool, error) {\n\targ := %s{", p.cursor, elem, p.params)
	for _, o := range p.owners {
		fmt.Fprintf(b, "%s: %s, ", o.field, o.arg)
	}
	fmt.Fprintf(b, `%s: int32(size) + 1}
	if after != nil {
		arg.%s = pgtype.Timestamptz{Time: after.At, Valid: true}
		arg.%s = pgtype.UUID{Bytes: after.ID, Valid: true}
	}
	rows, err := q.%s(ctx, arg)
	if err != nil {
		// Shapes only, never a parameter: a query value can be a person's
		// name or a token, and diag.Wrap's contract is that a fact rides the
		// chain because a caller NAMED it.
		return nil, false, diag.Wrap(%sError(err), "query %s", "size", size, "cursor", after != nil)
	}
	if len(rows) > size {
		return rows[:size], true, nil
	}
	return rows, false, nil
}
`, p.limitField, p.atField, p.idField, p.query, t.export, p.query)
}

func emitFactory(t *tableGen, genImport string) string {
	// The column values come first: which imports the file needs is decided
	// by the literals it ends up holding, and an override can retire the last
	// pgtype in a factory as easily as it can introduce a uuid.
	var fills strings.Builder
	needs := map[string]bool{}
	for _, f := range t.fills {
		fmt.Fprintf(&fills, "\t\t%s: %s,\n", f.field, f.expr)
		for _, imp := range f.needs {
			needs[imp] = true
		}
	}
	std, ext := []string{"context", "testing"}, []string{genImport}
	for imp := range needs {
		if strings.Contains(imp, ".") {
			ext = append(ext, imp)
		} else {
			std = append(std, imp)
		}
	}

	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package factory\n\n")
	writeImports(&b, std, ext)

	// Row spelling follows sqlc's own: *gen.Note when the product's gen.go
	// says emit_result_struct_pointers, gen.Note otherwise.
	row := "gen." + t.model
	if t.types.resultPointers {
		row = "*gen." + t.model
	}
	fmt.Fprintf(&b, `// %s inserts one %s row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func %s(t testing.TB, db gen.DBTX, mut ...func(*gen.%sParams)) %s {
	t.Helper()
	n := next(t, %q)
	arg := gen.%sParams{
`, t.model, t.name, t.model, t.create.Name, row, t.name, t.create.Name)

	b.WriteString(fills.String())
	fmt.Fprintf(&b, `	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).%s(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.%s: %%v", err)
	}
	return row
}

// %sN inserts count rows, ascending — the shape a paging test wants.
func %sN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.%sParams)) []%s {
	t.Helper()
	rows := make([]%s, 0, count)
	for range count {
		rows = append(rows, %s(t, db, mut...))
	}
	return rows
}
`, t.create.Name, t.model, t.model, t.model, t.create.Name, row, row, t.model)
	return b.String()
}

func emitFactoryShared() string {
	return genHeader + `// Package factory builds rows the schema will accept, so a test can state
// only what it is actually about. Import it from _test files ONLY — it links
// testing, and test-only code must never reach the product binary.
package factory

import (
	"encoding/binary"
	"hash/fnv"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// epoch anchors every generated timestamp: fixed, so an assertion can name a
// value, and ascending by sequence, so rows page in insertion order.
var epoch = time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)

func at(n int64) time.Time { return epoch.Add(time.Duration(n) * time.Second) }

// ptr fills a NULLABLE column: with emit_pointers_for_null_types sqlc spells
// those *T, and a factory always has a value to point at.
func ptr[T any](v T) *T { return &v }

// seqs is the per-test, per-table counter. Keying on the testing.TB is what
// makes parallel tests independent; the cleanup keeps a long package run from
// retaining every test that ever asked for a row.
var seqs sync.Map // seqKey -> *atomic.Int64

type seqKey struct {
	t     testing.TB
	table string
}

func next(t testing.TB, table string) int64 {
	key := seqKey{t, table}
	v, loaded := seqs.LoadOrStore(key, new(atomic.Int64))
	if !loaded {
		t.Cleanup(func() { seqs.Delete(key) })
	}
	return v.(*atomic.Int64).Add(1)
}

// uuidAt is a deterministic v4-shaped UUID: the table name mixed into the
// high half, the sequence in the low half, so two tables' first rows differ.
func uuidAt(table string, n int64) pgtype.UUID {
	h := fnv.New64a()
	h.Write([]byte(table))
	var b [16]byte
	binary.BigEndian.PutUint64(b[:8], h.Sum64())
	binary.BigEndian.PutUint64(b[8:], uint64(n))
	b[6] = b[6]&0x0f | 0x40
	b[8] = b[8]&0x3f | 0x80
	return pgtype.UUID{Bytes: b, Valid: true}
}
`
}
