package main

// What the ultra sqlc plugin writes.
//
// sqlc's own Go codegen answers "what do these queries look like in Go". It
// stops exactly where every product then writes the same four things by hand:
// a handle that can open a transaction, a bridge for work that must commit
// with the caller, keyset paging around a cursor query, and test rows the
// schema will accept. Those four are DERIVABLE from the schema sqlc already
// parsed, so they are generated here rather than remembered per product.
//
// Nothing in this file guesses: a wrapper appears when a query's compiled
// shape proves it is a keyset page, a sentinel appears when the migration
// declares the constraint, a factory appears when every NOT NULL column has a
// deterministic value. A table that fails a test gets NO output and a named
// reason in ultra.go — silence would be the one failure mode worse than the
// hand-written code this replaces.

import (
	"fmt"
	"go/format"
	"regexp"
	"slices"
	"sort"
	"strings"
	"unicode"
)

// genHeader tops every emitted file. It says which tool and which command —
// an agent that finds this file must not edit it, and must know the verb.
const genHeader = "// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate\n\n"

// pgType is one Postgres type's Go rendering: the type sqlc's pgx/v5 driver
// emits for a NOT NULL column, and a deterministic literal for a factory.
// A type absent from this table is not guessed — its table loses its factory
// and says why.
type pgType struct {
	goType string
	// lit renders the factory value; seq is the counter variable in scope.
	lit func(table, col, seq string) string
}

var pgTypes = map[string]pgType{
	"text":        {"string", strLit},
	"varchar":     {"string", strLit},
	"bpchar":      {"string", strLit},
	"char":        {"string", strLit},
	"name":        {"string", strLit},
	"citext":      {"string", strLit},
	"bool":        {"bool", func(_, _, _ string) string { return "false" }},
	"boolean":     {"bool", func(_, _, _ string) string { return "false" }},
	"int2":        {"int16", func(_, _, seq string) string { return "int16(" + seq + ")" }},
	"smallint":    {"int16", func(_, _, seq string) string { return "int16(" + seq + ")" }},
	"int4":        {"int32", func(_, _, seq string) string { return "int32(" + seq + ")" }},
	"integer":     {"int32", func(_, _, seq string) string { return "int32(" + seq + ")" }},
	"int8":        {"int64", func(_, _, seq string) string { return seq }},
	"bigint":      {"int64", func(_, _, seq string) string { return seq }},
	"float4":      {"float32", func(_, _, seq string) string { return "float32(" + seq + ")" }},
	"real":        {"float32", func(_, _, seq string) string { return "float32(" + seq + ")" }},
	"float8":      {"float64", func(_, _, seq string) string { return "float64(" + seq + ")" }},
	"uuid":        {"pgtype.UUID", func(table, _, seq string) string { return fmt.Sprintf("uuidAt(%q, %s)", table, seq) }},
	"timestamptz": {"pgtype.Timestamptz", tsLit},
	"timestamp":   {"pgtype.Timestamp", func(_, _, seq string) string { return "pgtype.Timestamp{Time: at(" + seq + "), Valid: true}" }},
	"date":        {"pgtype.Date", func(_, _, seq string) string { return "pgtype.Date{Time: at(" + seq + "), Valid: true}" }},
	"json":        {"[]byte", func(_, _, _ string) string { return `[]byte("{}")` }},
	"jsonb":       {"[]byte", func(_, _, _ string) string { return `[]byte("{}")` }},
	"bytea":       {"[]byte", func(table, col, seq string) string { return "[]byte(" + strLit(table, col, seq) + ")" }},
}

func strLit(table, col, seq string) string {
	return fmt.Sprintf("fmt.Sprintf(%q, %s)", table+"-"+col+"-%d", seq)
}

func tsLit(_, _, seq string) string {
	return "pgtype.Timestamptz{Time: at(" + seq + "), Valid: true}"
}

// ---- the analysis ----

// tableGen is everything the emitter concluded about one table.
type tableGen struct {
	name   string // the SQL table, "notes"
	model  string // sqlc's row struct, "Note"
	export string // the plural Go stem for this table's symbols, "Notes"
	cols   []sqlcColumn

	uniques []uniqueGen
	pages   []pageGen
	create  *sqlcQuery        // the insert this table's factory drives
	fkByCol map[string]string // column -> the parent table a factory must create first
	// noFactory, when set, is the reason — reported in ultra.go rather than
	// swallowed, so "where is my factory" is never a mystery.
	noFactory string
}

type uniqueGen struct {
	constraint string // exactly what pgconn.PgError.ConstraintName carries
	sentinel   string // ErrNotesSubjectTaken
	cols       []string
}

// pageGen is one query whose compiled shape IS a keyset page.
type pageGen struct {
	query                        string // ListNotes
	cursor                       string // NotesCursor
	row                          string // the element type of the generated method's result
	params                       string // ListNotesParams
	atField, idField, limitField string
	owners                       []ownerArg
}

type ownerArg struct {
	arg    string // the Go parameter, lower camel
	field  string // the params struct field
	goType string
}

// analyze turns a decoded request plus the schema facts scraped from the
// migrations into the per-table plan the emitters render.
func analyze(req *sqlcRequest, facts schemaFacts) []tableGen {
	schema := req.Catalog.DefaultSchema
	if schema == "" {
		schema = "public"
	}
	var out []tableGen
	for _, s := range req.Catalog.Schemas {
		if s.Name != schema {
			continue // pg_catalog and friends ride along in every request
		}
		for _, t := range s.Tables {
			g := tableGen{
				name:    t.Rel.Name,
				model:   modelName(t.Rel.Name),
				export:  goName(t.Rel.Name),
				cols:    t.Columns,
				fkByCol: facts.fks[t.Rel.Name],
			}
			for _, u := range facts.uniques[g.name] {
				g.uniques = append(g.uniques, uniqueGen{
					constraint: u.name,
					sentinel:   sentinelName(u),
					cols:       u.cols,
				})
			}
			out = append(out, g)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })

	byName := map[string]*tableGen{}
	for i := range out {
		byName[out[i].name] = &out[i]
	}
	for i := range req.Queries {
		q := &req.Queries[i]
		if q.InsertIntoTable != nil {
			if g := byName[q.InsertIntoTable.Name]; g != nil && g.create == nil && q.Cmd == ":one" {
				g.create = q
			}
			continue
		}
		p, table := detectPage(q, byName)
		if p != nil {
			table.pages = append(table.pages, *p)
		}
	}
	for i := range out {
		out[i].noFactory = factoryBlocker(&out[i], byName)
	}
	return out
}

// sentinelName turns a constraint into a Go sentinel: notes_subject_key
// becomes ErrNotesSubjectTaken. The DB object's own name is the source, so
// the sentinel and the error Postgres reports can never drift apart.
func sentinelName(u uniqueFact) string {
	stem := u.name
	for _, suffix := range []string{"_key", "_idx", "_index", "_unique", "_uniq", "_uq"} {
		stem = strings.TrimSuffix(stem, suffix)
	}
	return "Err" + goName(stem) + "Taken"
}

// tupleRe finds a keyset tuple compare: (created_at, id) < (…, …).
var tupleRe = regexp.MustCompile(`\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*[<>]\s*\(`)

// detectPage reports whether a compiled query IS a keyset page over one
// table: a :many with a nullable (timestamptz, uuid) narg pair compared as a
// tuple against the columns it orders by, plus an integer limit. Shape, not
// naming — a query that merely mentions a cursor gets nothing.
func detectPage(q *sqlcQuery, byName map[string]*tableGen) (*pageGen, *tableGen) {
	if q.Cmd != ":many" || len(q.Columns) == 0 {
		return nil, nil
	}
	tuple := tupleRe.FindStringSubmatch(strings.ToLower(q.Text))
	if tuple == nil || !strings.Contains(strings.ToLower(q.Text), "order by") {
		return nil, nil
	}
	var at, id, limit *sqlcColumn
	var owners []sqlcColumn
	for i := range q.Params {
		c := q.Params[i].Column
		switch {
		case c.IsNamedParam && !c.NotNull && baseType(c.Type.Name) == "timestamptz" && at == nil:
			at = &q.Params[i].Column
		case c.IsNamedParam && !c.NotNull && baseType(c.Type.Name) == "uuid" && id == nil:
			id = &q.Params[i].Column
		case !c.IsNamedParam && isIntType(baseType(c.Type.Name)) && limit == nil:
			limit = &q.Params[i].Column
		default:
			owners = append(owners, c)
		}
	}
	if at == nil || id == nil || limit == nil {
		return nil, nil
	}
	// The tuple must be the ORDER BY, or the "one row past the end" trick
	// reads a page nobody asked for.
	order := strings.ToLower(q.Text[strings.LastIndex(strings.ToLower(q.Text), "order by"):])
	if !strings.Contains(order, tuple[1]) || !strings.Contains(order, tuple[2]) {
		return nil, nil
	}
	table := byName[q.Columns[0].Table.GetName()]
	if table == nil {
		return nil, nil
	}
	p := pageGen{
		query:      q.Name,
		cursor:     strings.TrimPrefix(q.Name, "List") + "Cursor",
		row:        rowType(q, table),
		params:     q.Name + "Params",
		atField:    goName(at.Name),
		idField:    goName(id.Name),
		limitField: goName(limit.Name),
	}
	for _, c := range owners {
		t, ok := pgTypes[baseType(c.Type.Name)]
		if !ok || !c.NotNull || c.IsArray {
			return nil, nil // an owner we cannot type is not a page we can write
		}
		p.owners = append(p.owners, ownerArg{arg: lowerCamel(goName(c.Name)), field: goName(c.Name), goType: t.goType})
	}
	return &p, table
}

// rowType is the element type of the generated method's slice: sqlc reuses
// the table's model when a query returns that table's columns unchanged
// (`select *`), and mints <Query>Row otherwise.
func rowType(q *sqlcQuery, t *tableGen) string {
	if len(q.Columns) != len(t.cols) {
		return q.Name + "Row"
	}
	for i, c := range q.Columns {
		if c.Name != t.cols[i].Name || c.Table.GetName() != t.name {
			return q.Name + "Row"
		}
	}
	return t.model
}

func (i *sqlcIdent) GetName() string {
	if i == nil {
		return ""
	}
	return i.Name
}

// factoryBlocker returns why this table gets no factory, or "" when it does.
func factoryBlocker(t *tableGen, byName map[string]*tableGen) string {
	if t.create == nil {
		return "no :one insert query — a factory has nothing to call"
	}
	for _, p := range t.create.Params {
		c := p.Column
		if parent := t.fkByCol[c.Name]; parent != "" {
			g := byName[parent]
			switch {
			case parent == t.name:
				return fmt.Sprintf("column %s references its own table — a factory would not terminate", c.Name)
			case g == nil || g.create == nil:
				return fmt.Sprintf("column %s references %s, which has no factory of its own", c.Name, parent)
			case !slices.ContainsFunc(g.cols, func(p sqlcColumn) bool { return p.Name == "id" }):
				return fmt.Sprintf("column %s references %s, which has no id column to take", c.Name, parent)
			}
			continue
		}
		if c.IsArray {
			return fmt.Sprintf("column %s is an array — no defensible default", c.Name)
		}
		if _, ok := pgTypes[baseType(c.Type.Name)]; !ok {
			return fmt.Sprintf("column %s is %s, which has no deterministic default", c.Name, c.Type.Name)
		}
	}
	return ""
}

func baseType(s string) string {
	if i := strings.LastIndex(s, "."); i >= 0 {
		s = s[i+1:]
	}
	return strings.ToLower(s)
}

func isIntType(s string) bool {
	switch s {
	case "int2", "int4", "int8", "smallint", "integer", "bigint":
		return true
	}
	return false
}

func lowerCamel(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	// An initialism keeps its shape until the first lowercase run: IDToken
	// becomes idToken, ID becomes id.
	i := 0
	for i < len(r) && unicode.IsUpper(r[i]) {
		i++
	}
	if i > 1 && i < len(r) {
		i--
	}
	for j := 0; j < i; j++ {
		r[j] = unicode.ToLower(r[j])
	}
	return goKeyword(string(r))
}

// goKeyword keeps a column named `type` or `range` from becoming an illegal
// parameter name.
func goKeyword(s string) string {
	switch s {
	case "break", "case", "chan", "const", "continue", "default", "defer", "else",
		"fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
		"map", "package", "range", "return", "select", "struct", "switch", "type", "var":
		return s + "_"
	}
	return s
}

// ---- the emitters ----

// emitAll renders every file the plugin contributes. genImport is the import
// path of the sqlc output package, which the factory package needs.
func emitAll(tables []tableGen, genImport string) ([]outFile, error) {
	files := []outFile{}
	shared, err := gofmtGo(emitShared(tables))
	if err != nil {
		return nil, err
	}
	files = append(files, outFile{"ultra.go", shared})

	var factories []outFile
	// Every table gets a file even with no constraints and no page query: the
	// 42P01 arm alone is worth a classifier, and its absence would read as a
	// table the plugin failed to see.
	for i := range tables {
		t := &tables[i]
		body, err := gofmtGo(emitTable(t))
		if err != nil {
			return nil, fmt.Errorf("table %s: %w", t.name, err)
		}
		files = append(files, outFile{"ultra_" + t.name + ".go", body})
		if t.noFactory != "" {
			continue
		}
		f, err := gofmtGo(emitFactory(t, genImport))
		if err != nil {
			return nil, fmt.Errorf("factory %s: %w", t.name, err)
		}
		factories = append(factories, outFile{"factory/" + t.name + ".go", f})
	}
	if len(factories) > 0 {
		base, err := gofmtGo(emitFactoryShared())
		if err != nil {
			return nil, err
		}
		files = append(files, outFile{"factory/ultra.go", base})
		files = append(files, factories...)
	}
	return files, nil
}

// writeImports renders the two groups gofmt would not reorder for us —
// stdlib, blank line, everything else — each sorted.
func writeImports(b *strings.Builder, std, ext []string) {
	sort.Strings(std)
	sort.Strings(ext)
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString("\n")
	for _, p := range ext {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
}

func gofmtGo(src string) ([]byte, error) {
	b, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("the plugin rendered invalid Go: %w\n%s", err, src)
	}
	return b, nil
}

func emitShared(tables []tableGen) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString(`package gen

import (
	"context"
	"errors"

	"github.com/bronystylecrazy/ultrastack/contrib/pg"
	"github.com/jackc/pgx/v5"
)

// DB is the product's one handle on Postgres, and the only thing a Store
// holds. It reaches a querier two ways and no third: Q() for a single
// statement, Atomic() for a unit of work.
type DB struct{ db *pg.DB }

func NewDB(db *pg.DB) *DB { return &DB{db: db} }

// Q is the querier outside a transaction — one statement is already atomic.
func (d *DB) Q() *Queries { return New(d.db.Pool) }

// Atomic runs fn as one transaction: commit when it returns nil, roll back
// otherwise. fn MAY RUN TWICE, because a serialization failure is retried —
// so it must carry no state across the call and do nothing outside the
// database (no publish, no email, no counter).
func (d *DB) Atomic(ctx context.Context, fn func(*Queries) error) error {
	return pg.Atomic(ctx, d.db, func(tx pgx.Tx) error { return fn(New(tx)) })
}

// Tx exposes the handle this querier runs on, so work that must commit WITH
// the caller (jobs.EnqueueTx) joins the transaction instead of opening a
// second one that can commit alone.
func (q *Queries) Tx() DBTX { return q.db }

// ErrSchemaBehind is what 42P01 means in practice: the binary is ahead of the
// database. Every <Table>Error maps it, so no product learns the code.
var ErrSchemaBehind = errors.New("relation does not exist — run ./app migrate up")
`)
	var skipped []string
	for _, t := range tables {
		if t.noFactory != "" {
			skipped = append(skipped, fmt.Sprintf("//   %s — %s", t.name, t.noFactory))
		}
	}
	if len(skipped) > 0 {
		b.WriteString("\n// Tables with no generated factory, and why. Write one by hand in a\n" +
			"// _test file, or give the column a type this generator can default:\n")
		b.WriteString(strings.Join(skipped, "\n"))
		b.WriteString("\n")
	}
	return b.String()
}

func emitTable(t *tableGen) string {
	var b strings.Builder
	b.WriteString(genHeader)
	std, ext := []string{"errors"}, []string{"github.com/jackc/pgx/v5/pgconn"}
	if len(t.pages) > 0 {
		std = append(std, "context", "time")
		ext = append(ext, "github.com/bronystylecrazy/ultrastack/di/diag",
			"github.com/google/uuid", "github.com/jackc/pgx/v5/pgtype")
	}
	b.WriteString("package gen\n\n")
	writeImports(&b, std, ext)

	for _, u := range t.uniques {
		fmt.Fprintf(&b, "// %s is unique constraint %s (%s).\nvar %s = errors.New(%q)\n\n",
			u.sentinel, u.constraint, strings.Join(u.cols, ", "), u.sentinel,
			t.name+": "+strings.Join(u.cols, ", ")+" already taken")
	}

	fmt.Fprintf(&b, `// %sError names what Postgres refused, so a feature branches on a sentinel
// instead of matching driver strings. Anything unrecognized is returned
// UNCHANGED — errors.Is and errors.As still reach the driver error underneath.
func %sError(err error) error {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return err
	}
	if pgErr.Code == "42P01" {
		return ErrSchemaBehind
	}
`, t.export, t.export)
	if len(t.uniques) > 0 {
		b.WriteString("\tswitch pgErr.ConstraintName {\n")
		for _, u := range t.uniques {
			fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %s\n", u.constraint, u.sentinel)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn err\n}\n")

	for _, p := range t.pages {
		emitPage(&b, t, p)
	}
	return b.String()
}

func emitPage(b *strings.Builder, t *tableGen, p pageGen) {
	fmt.Fprintf(b, `
// %s is one page boundary: the ordering tuple of the last row handed out.
// It is a VALUE, not an offset — a row inserted meanwhile shifts no page.
type %s struct {
	At time.Time
	ID uuid.UUID
}

// %sPage runs %s one row past size, so "is there more" costs no second
// query and no count. A nil cursor starts at the first page.
func (q *Queries) %sPage(ctx context.Context`, p.cursor, p.cursor, p.query, p.query, p.query)
	for _, o := range p.owners {
		fmt.Fprintf(b, ", %s %s", o.arg, o.goType)
	}
	fmt.Fprintf(b, ", after *%s, size int) ([]%s, bool, error) {\n\targ := %s{", p.cursor, p.row, p.params)
	for _, o := range p.owners {
		fmt.Fprintf(b, "%s: %s, ", o.field, o.arg)
	}
	fmt.Fprintf(b, `%s: int32(size) + 1}
	if after != nil {
		arg.%s = pgtype.Timestamptz{Time: after.At, Valid: true}
		arg.%s = pgtype.UUID{Bytes: after.ID, Valid: true}
	}
	rows, err := q.%s(ctx, arg)
	if err != nil {
		// Shapes only, never a parameter: a query value can be a person's
		// name or a token, and diag.Wrap's contract is that a fact rides the
		// chain because a caller NAMED it.
		return nil, false, diag.Wrap(%sError(err), "query %s", "size", size, "cursor", after != nil)
	}
	if len(rows) > size {
		return rows[:size], true, nil
	}
	return rows, false, nil
}
`, p.limitField, p.atField, p.idField, p.query, t.export, p.query)
}

func emitFactory(t *tableGen, genImport string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package factory\n\n")
	writeImports(&b, []string{"context", "fmt", "testing"},
		[]string{genImport, "github.com/jackc/pgx/v5/pgtype"})

	fmt.Fprintf(&b, `// %s inserts one %s row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func %s(t testing.TB, db gen.DBTX, mut ...func(*gen.%sParams)) gen.%s {
	t.Helper()
	n := next(t, %q)
	arg := gen.%sParams{
`, t.model, t.name, t.model, t.create.Name, t.model, t.name, t.create.Name)

	for _, p := range t.create.Params {
		c := p.Column
		if parent := t.fkByCol[c.Name]; parent != "" {
			fmt.Fprintf(&b, "\t\t%s: %s(t, db).ID,\n", goName(c.Name), modelName(parent))
			continue
		}
		fmt.Fprintf(&b, "\t\t%s: %s,\n", goName(c.Name),
			pgTypes[baseType(c.Type.Name)].lit(t.name, c.Name, "n"))
	}
	fmt.Fprintf(&b, `	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).%s(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.%s: %%v", err)
	}
	return row
}

// %sN inserts count rows, ascending — the shape a paging test wants.
func %sN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.%sParams)) []gen.%s {
	t.Helper()
	rows := make([]gen.%s, 0, count)
	for range count {
		rows = append(rows, %s(t, db, mut...))
	}
	return rows
}
`, t.create.Name, t.model, t.model, t.model, t.create.Name, t.model, t.model, t.model)
	return b.String()
}

func emitFactoryShared() string {
	return genHeader + `// Package factory builds rows the schema will accept, so a test can state
// only what it is actually about. Import it from _test files ONLY — it links
// testing, and test-only code must never reach the product binary.
package factory

import (
	"encoding/binary"
	"hash/fnv"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// epoch anchors every generated timestamp: fixed, so an assertion can name a
// value, and ascending by sequence, so rows page in insertion order.
var epoch = time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)

func at(n int64) time.Time { return epoch.Add(time.Duration(n) * time.Second) }

// seqs is the per-test, per-table counter. Keying on the testing.TB is what
// makes parallel tests independent; the cleanup keeps a long package run from
// retaining every test that ever asked for a row.
var seqs sync.Map // seqKey -> *atomic.Int64

type seqKey struct {
	t     testing.TB
	table string
}

func next(t testing.TB, table string) int64 {
	key := seqKey{t, table}
	v, loaded := seqs.LoadOrStore(key, new(atomic.Int64))
	if !loaded {
		t.Cleanup(func() { seqs.Delete(key) })
	}
	return v.(*atomic.Int64).Add(1)
}

// uuidAt is a deterministic v4-shaped UUID: the table name mixed into the
// high half, the sequence in the low half, so two tables' first rows differ.
func uuidAt(table string, n int64) pgtype.UUID {
	h := fnv.New64a()
	h.Write([]byte(table))
	var b [16]byte
	binary.BigEndian.PutUint64(b[:8], h.Sum64())
	binary.BigEndian.PutUint64(b[8:], uint64(n))
	b[6] = b[6]&0x0f | 0x40
	b[8] = b[8]&0x3f | 0x80
	return pgtype.UUID{Bytes: b, Valid: true}
}
`
}
