// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"fmt"
	"testing"

	"example.com/nullable/gen"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Gizmo inserts one gizmos row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Gizmo(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateGizmoParams)) gen.Gizmo {
	t.Helper()
	n := next(t, "gizmos")
	arg := gen.CreateGizmoParams{
		Subject:   fmt.Sprintf("gizmos-subject-%d", n),
		Label:     ptr(fmt.Sprintf("gizmos-label-%d", n)),
		Tally:     ptr(int32(n)),
		Ratio:     ptr(float64(n)),
		Active:    ptr(false),
		Tag:       uuid.UUID(uuidAt("gizmos", n).Bytes),
		SeenAt:    pgtype.Timestamptz{Time: at(n), Valid: true},
		Payload:   []byte("{}"),
		CreatedAt: at(n),
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateGizmo(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Gizmo: %v", err)
	}
	return row
}

// GizmoN inserts count rows, ascending — the shape a paging test wants.
func GizmoN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateGizmoParams)) []gen.Gizmo {
	t.Helper()
	rows := make([]gen.Gizmo, 0, count)
	for range count {
		rows = append(rows, Gizmo(t, db, mut...))
	}
	return rows
}
