// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"fmt"
	"testing"

	"example.com/nullable/gen"
)

// Gadget inserts one gadgets row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Gadget(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateGadgetParams)) gen.Gadget {
	t.Helper()
	n := next(t, "gadgets")
	arg := gen.CreateGadgetParams{
		GizmoID:   Gizmo(t, db).ID,
		Note:      ptr(fmt.Sprintf("gadgets-note-%d", n)),
		CreatedAt: at(n),
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateGadget(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Gadget: %v", err)
	}
	return row
}

// GadgetN inserts count rows, ascending — the shape a paging test wants.
func GadgetN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateGadgetParams)) []gen.Gadget {
	t.Helper()
	rows := make([]gen.Gadget, 0, count)
	for range count {
		rows = append(rows, Gadget(t, db, mut...))
	}
	return rows
}
