// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package gen

import (
	"context"
	"errors"

	"github.com/bronystylecrazy/ultrastack/contrib/pg"
	"github.com/jackc/pgx/v5"
)

// DB is the product's one handle on Postgres, and the only thing a Store
// holds. It reaches a querier two ways and no third: Q() for a single
// statement, Atomic() for a unit of work.
type DB struct{ db *pg.DB }

func NewDB(db *pg.DB) *DB { return &DB{db: db} }

// Q is the querier outside a transaction — one statement is already atomic.
func (d *DB) Q() *Queries { return New(d.db.Pool) }

// Atomic runs fn as one transaction: commit when it returns nil, roll back
// otherwise. fn MAY RUN TWICE, because a serialization failure is retried —
// so it must carry no state across the call and do nothing outside the
// database (no publish, no email, no counter).
func (d *DB) Atomic(ctx context.Context, fn func(*Queries) error) error {
	return pg.Atomic(ctx, d.db, func(tx pgx.Tx) error { return fn(New(tx)) })
}

// Tx exposes the handle this querier runs on, so work that must commit WITH
// the caller (jobs.EnqueueTx) joins the transaction instead of opening a
// second one that can commit alone.
func (q *Queries) Tx() DBTX { return q.db }

// ErrSchemaBehind is what 42P01 means in practice: the binary is ahead of the
// database. Every <Table>Error maps it, so no product learns the code.
var ErrSchemaBehind = errors.New("relation does not exist — run ./app migrate up")
