// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"testing"

	"example.com/overrides/gen"
)

// Quack inserts one quacks row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Quack(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateQuackParams)) gen.Quack {
	t.Helper()
	n := next(t, "quacks")
	arg := gen.CreateQuackParams{
		DuckID:    Duck(t, db).ID,
		Loudness:  int32(n),
		CreatedAt: at(n),
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateQuack(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Quack: %v", err)
	}
	return row
}

// QuackN inserts count rows, ascending — the shape a paging test wants.
func QuackN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateQuackParams)) []gen.Quack {
	t.Helper()
	rows := make([]gen.Quack, 0, count)
	for range count {
		rows = append(rows, Quack(t, db, mut...))
	}
	return rows
}
