// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package factory

import (
	"context"
	"fmt"
	"testing"

	"example.com/overrides/gen"
	"github.com/google/uuid"
)

// Duck inserts one ducks row. Every column the insert demands is filled
// deterministically; the mutators carry the value the test is ABOUT and run
// last, so a test states only what it is testing.
func Duck(t testing.TB, db gen.DBTX, mut ...func(*gen.CreateDuckParams)) gen.Duck {
	t.Helper()
	n := next(t, "ducks")
	arg := gen.CreateDuckParams{
		Subject:   fmt.Sprintf("ducks-subject-%d", n),
		OwnerID:   uuid.UUID(uuidAt("ducks", n).Bytes),
		Name:      fmt.Sprintf("ducks-name-%d", n),
		Weight:    int32(n),
		CreatedAt: at(n),
	}
	for _, m := range mut {
		m(&arg)
	}
	row, err := gen.New(db).CreateDuck(context.Background(), arg)
	if err != nil {
		t.Fatalf("factory.Duck: %v", err)
	}
	return row
}

// DuckN inserts count rows, ascending — the shape a paging test wants.
func DuckN(t testing.TB, db gen.DBTX, count int, mut ...func(*gen.CreateDuckParams)) []gen.Duck {
	t.Helper()
	rows := make([]gen.Duck, 0, count)
	for range count {
		rows = append(rows, Duck(t, db, mut...))
	}
	return rows
}
