// Code generated by sqlc (ultra plugin). DO NOT EDIT — regenerate: sqlc generate

package gen

import (
	"context"
	"errors"
	"time"

	"github.com/bronystylecrazy/ultrastack/di/diag"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

// ErrDucksSubjectNameTaken is unique constraint ducks_subject_name_key (subject, name).
var ErrDucksSubjectNameTaken = errors.New("ducks: subject, name already taken")

// DucksError names what Postgres refused, so a feature branches on a sentinel
// instead of matching driver strings. Anything unrecognized is returned
// UNCHANGED — errors.Is and errors.As still reach the driver error underneath.
func DucksError(err error) error {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return err
	}
	if pgErr.Code == "42P01" {
		return ErrSchemaBehind
	}
	switch pgErr.ConstraintName {
	case "ducks_subject_name_key":
		return ErrDucksSubjectNameTaken
	}
	return err
}

// DucksCursor is one page boundary: the ordering tuple of the last row handed out.
// It is a VALUE, not an offset — a row inserted meanwhile shifts no page.
type DucksCursor struct {
	At time.Time
	ID uuid.UUID
}

// ListDucksPage runs ListDucks one row past size, so "is there more" costs no second
// query and no count. A nil cursor starts at the first page.
func (q *Queries) ListDucksPage(ctx context.Context, subject string, after *DucksCursor, size int) ([]Duck, bool, error) {
	arg := ListDucksParams{Subject: subject, Limit: int32(size) + 1}
	if after != nil {
		arg.AfterAt = pgtype.Timestamptz{Time: after.At, Valid: true}
		arg.AfterID = pgtype.UUID{Bytes: after.ID, Valid: true}
	}
	rows, err := q.ListDucks(ctx, arg)
	if err != nil {
		// Shapes only, never a parameter: a query value can be a person's
		// name or a token, and diag.Wrap's contract is that a fact rides the
		// chain because a caller NAMED it.
		return nil, false, diag.Wrap(DucksError(err), "query ListDucks", "size", size, "cursor", after != nil)
	}
	if len(rows) > size {
		return rows[:size], true, nil
	}
	return rows, false, nil
}
